name: D
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.0.5
      with:
        compiler: dmd-latest
    - name: 'Build & Test'
      run: |
        dub build --compiler=$DC
        dub test --compiler=$DC --config=example
